spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.biao.qian.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
   profiles: dev
  application: 
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 200
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
   app.name: biao-microservercloud
   company.name: biao.qian
   company.artifacId: $project.artifactId$
   build.version: $project.version$ 
---
server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.biao.qian.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
   profiles: test
  application: 
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 200
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
   app.name: biao-microservercloud
   company.name: biao.qian
   company.artifacId: $project.artifactId$
   build.version: $project.version$ 

